<?php
/* -- CONFIG -- */
$GLOBALS["MAXIUMUM_ATTACHMENTS"] = 8;

$GLOBALS["CHAT_FILE_NAME"] = "chat";
$GLOBALS["CHAT_MAXIMUM_MESSAGES"] = 30;
$GLOBALS["CHAT_MAXLENGTH_AUTHOR"] = 20;
$GLOBALS["CHAT_MAXLENGTH_MSG"] = 250;
$GLOBALS["CHAT_TIME_TO_REFRESH"] = 2.5; // seconds. MAX 28
$GLOBALS["CHAT_SEPARATOR"] = ": ";

?>